name = ""
main = "packages/upstreet-agent/main.jsx"
compatibility_date = "2023-11-21"
node_compat = true
workers_dev = true

[[durable_objects.bindings]]
name = "AGENT"
class_name = "DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["DurableObject"]

[vars]
AGENT_JSON = ""
WALLET_MNEMONIC = ""
AGENT_TOKEN = ""
SUPABASE_URL = "https://friddlbqibjnxjoxeocc.supabase.co"
SUPABASE_PUBLIC_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaWRkbGJxaWJqbnhqb3hlb2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDM2NjE3NDIsImV4cCI6MjAxOTIzNzc0Mn0.jnvk5X27yFTcJ6jsCkuXOog1ZN825md4clvWuGQ8DMI"
WORKER_ENV = "production"